In [3]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
df= pd.read_csv('IMDB dataset.csv')

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.shape

(50000, 2)

In [8]:
df= df.head(100)

In [10]:
df.shape

(100, 2)

# Data preprocesing

In [14]:
# lowercase
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [12]:
df['review'] = df['review'].str.lower()

In [15]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

In [16]:
# remove html tags

import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [18]:
text= '<html><body><p> Movie reviews <p><boody><html>'

In [19]:
remove_html_tags(text)

' Movie reviews '

In [21]:
df['review'] = df['review'].apply(remove_html_tags)

In [22]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [23]:
# remove url
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www.\.\S+')
    return pattern.sub(r'',text)

In [29]:
text1 = 'check out my linkdein https://www.linkedin.com/in/amanpy45/ aman negi'

In [30]:
remove_url(text1)

'check out my linkdein  aman negi'

In [31]:
# punctuation handling

import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [32]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
def remove_punctuation(text):
    for char in exclude:
        text= text.replace(char,'')
    return text

In [36]:
text = 'string. with. punctuation'

In [37]:
start = time.time()
print(remove_punctuation(text))
time1 = time.time() - start
print(time1 * 50000)

string with punctuation
0.0

In [39]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [41]:
remove_punctuation(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

In [43]:
# handling chat conversion 

chat_words = {
    'ASAP': 'As Soon As Possible',
    'AFK': 'Away From Keyboard',
    'BTW': 'By The Way',
    'FYI': 'For Your Information',
    'IMO': 'In My Opinion',
    'NVM': 'Never Mind',
    'TBH': 'To Be Honest',
    'LOL': 'Laughing Out Loud',
    'IDK': 'I Don\'t Know',
    'SMH': 'Shaking My Head',
    'FR': 'For Real',
    'RN': 'Right Now',
    'BRB': 'Be Right Back',
    'TTYL': 'Talk To You Later',
    'ICYMI': 'In Case You Missed It',
    'TLDR': 'Too Long; Didn\'t Read',
    'TIA': 'Thanks In Advance',
    'JK': 'Just Kidding',
    'JIC': 'Just In Case',
    'FOMO': 'Fear Of Missing Out',
    'GG': 'Good Game',
    'GLHF': 'Good Luck Have Fun',
    'IRL': 'In Real Life',
    'LMK': 'Let Me Know',
    'MYOB': 'Mind Your Own Business',
    'OMG': 'Oh My God',
    'OTW': 'On The Way',
    'POV': 'Point Of View',
    'TMI': 'Too Much Information',
    'YW': 'You\'re Welcome'
}

In [48]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [49]:
chat_conversion('Do this work ASAP')

'Do this work As Soon As Possible'

In [57]:
%pip install TextBlob

Collecting TextBlob
  Using cached textblob-0.20.0-py3-none-any.whl.metadata (4.0 kB)
Collecting nltk>=3.9 (from TextBlob)
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from nltk>=3.9->TextBlob) (8.4.2)
Collecting joblib (from nltk>=3.9->TextBlob)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: regex>=2021.8.3 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from nltk>=3.9->TextBlob) (2026.6.28)
Requirement already satisfied: tqdm in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from nltk>=3.9->TextBlob) (4.68.3)
Requirement already satisfied: colorama in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from click->nltk>=3.9->TextBlob) (0.4.6)
Using cached textblob-0.20.0-py3-none-any.whl (624 kB)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: joblib, nltk, TextBlob
Successfully installed TextBlob-0.20.0 joblib-1.5.3 nltk-3.9.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [60]:
# incorrect_text handling

from textblob import TextBlob

incorrect_text = 'oncee apon a timee there wes a kingg living his heppy life withe his quen'

textblb = TextBlob(incorrect_text)

textblb.correct().string

'once upon a time there was a king living his happy life with his queen'

In [61]:
#stopwords

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [62]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [63]:
# this movie is awesome, i loved it
# for sentiment -> movie  awesome   loved is required 
# here no need stopwords, also inc dim

In [64]:
len(stopwords.words('english'))

198

In [65]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)

    x= new_text[:]
    new_text.clear()
    return " ".join(x)

In [69]:
remove_stopwords('this movie is awesome i loved it')

' movie  awesome  loved '

In [ ]:
# df['review'] = df['review'].apply(remove_stopwords)

In [75]:
# handle emoji

import re

def remove_emoji(text):
    emoji_pattern = re.compile('[\U0001F600\U0001F44D\U0001F680]')
    return emoji_pattern.sub(r'', text)

In [76]:
print(remove_emoji('Loved this movie. It was 👍 👍'))

Loved this movie. It was

In [77]:
remove_emoji (' you are the best 👍')

' you are the best '

In [81]:
%pip install emoji

Collecting emoji
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Using cached emoji-2.15.0-py3-none-any.whl (608 kB)
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [82]:
import emoji
print(emoji.demojize('Python is 👍'))

Python is :thumbs_up:

In [83]:
# tokenization

In [84]:
# 1. using ths split function

# word tokenization
sent1 = 'I am doing my homework'
sent1.split()

['I', 'am', 'doing', 'my', 'homework']

In [86]:
# sentence tokenization
sent2 = 'My name is Aman, I live in India, India is a diversed country, I am a student'
sent2.split(',')

['My name is Aman',
 ' I live in India',
 ' India is a diversed country',
 ' I am a student']

In [89]:
# using regular expression

# word tokenization
import re
sent3 = 'I am going to New Delhi'
tokens = re.findall(r"[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'New', 'Delhi']

In [92]:
# sentence tokenization
text = 'My name is Aman. I live in India. India is a diversed country. I am a student'
sentences = re.compile('[.!?]').split(text)
sentences

['My name is Aman',
 ' I live in India',
 ' India is a diversed country',
 ' I am a student']

In [93]:
# NLTK
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [95]:
# word tokenize
sent1 = ' I am going to New Delhi'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'New', 'Delhi']

In [96]:
# sentence tokenize
text = 'My name is Aman. I live in India. India is a diversed country. I am a student'
sent_tokenize(text)

['My name is Aman.',
 'I live in India.',
 'India is a diversed country.',
 'I am a student']

In [100]:
%pip install spacy

Collecting spacy
  Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Using cached weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Using cached confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (0.26.8)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (4.68.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (2.34.2)
Collecting pydantic<3.0.0,>=2.0.0 (from spacy)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: jinja2 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from spacy) (26.2)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached pydantic_core-2.46.4-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached smart_open-8.0.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: httpx>=0.24.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.1)
Requirement already satisfied: httpcore==1.* in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Downloading wrapt-2.2.2-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: mdurl~=0.1 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
    --------------------------------------- 0.3/14.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.2 MB 2.8 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/14.2 MB 1.4 MB/s eta 0:00:10
   -- ------------------------------------- 1.0/14.2 MB 1.5 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/14.2 MB 1.4 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/14.2 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.6/14.2 MB 1.8 MB/s eta 0:00:07
   -------- ------------------------------- 3.1/14.2 MB 2.0 MB/s eta 0:00:06
   -------- ------------------------------- 3.1/14.2 MB 2.0 MB/s eta 0:00:06
   -------- ------------------------------- 3.1/14.2 MB 2.0 MB/s eta 0:00:06
   -------- ------------------------------- 3.1/14.2 MB 2.0 MB/s eta 0:00:06
   --------- ------------------------------ 3.4/14.2 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 3.7/14.2 MB 1.4 MB/s eta 0:00:08
   ----------- ---------------------------- 3.9/14.2 MB 1.3 MB/s eta 0:00:08
   ----------- ---------------------------- 4.2/14.2 MB 1.3 MB/s eta 0:00:08
   ------------ --------------------------- 4.5/14.2 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 4.7/14.2 MB 1.3 MB/s eta 0:00:08
   -------------- ------------------------- 5.0/14.2 MB 1.3 MB/s eta 0:00:07
   --------------- ------------------------ 5.5/14.2 MB 1.3 MB/s eta 0:00:07
   ---------------- ----------------------- 5.8/14.2 MB 1.4 MB/s eta 0:00:07
   ---------------- ----------------------- 6.0/14.2 MB 1.4 MB/s eta 0:00:06
   ----------------- ---------------------- 6.3/14.2 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 6.6/14.2 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 6.6/14.2 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 6.6/14.2 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.8/14.2 MB 1.2 MB/s eta 0:00:07
   ------------------- -------------------- 6.8/14.2 MB 1.2 MB/s eta 0:00:07
   ------------------- -------------------- 7.1/14.2 MB 1.2 MB/s eta 0:00:07
   ------------------- -------------------- 7.1/14.2 MB 1.2 MB/s eta 0:00:07
   -------------------- ------------------- 7.3/14.2 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.3/14.2 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.3/14.2 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.3/14.2 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 7.3/14.2 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 7.6/14.2 MB 1.0 MB/s eta 0:00:07
   --------------------- ------------------ 7.6/14.2 MB 1.0 MB/s eta 0:00:07
   --------------------- ------------------ 7.6/14.2 MB 1.0 MB/s eta 0:00:07
   ---------------------- ----------------- 8.1/14.2 MB 996.7 kB/s eta 0:00:07
   ----------------------- ---------------- 8.4/14.2 MB 1.0 MB/s eta 0:00:06
   ------------------------- -------------- 8.9/14.2 MB 1.0 MB/s eta 0:00:06
   -------------------------- ------------- 9.4/14.2 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 10.0/14.2 MB 1.1 MB/s eta 0:00:04
   ------------------------------ --------- 10.7/14.2 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 11.0/14.2 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 11.5/14.2 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 11.5/14.2 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 11.5/14.2 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 11.5/14.2 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 11.8/14.2 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 12.1/14.2 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 12.3/14.2 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 12.3/14.2 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 12.6/14.2 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 12.8/14.2 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 13.1/14.2 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 13.4/14.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  13.9/14.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.2 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 1.1 MB/s eta 0:00:00
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl (122 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-win_amd64.whl (2.1 MB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl (652 kB)
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ------------------------------- ------- 524.3/652.5 kB 63.5 kB/s eta 0:00:03
   ------------------------------- ------- 524.3/652.5 kB 63.5 kB/s eta 0:00:03
   --------------------------------------- 652.5/652.5 kB 89.5 kB/s eta 0:00:00
Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------ --------------------------- 0.5/1.7 MB 226.8 kB/s eta 0:00:06
   ------------------ --------------------- 0.8/1.7 MB 229.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.8/1.7 MB 229.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.8/1.7 MB 229.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.8/1.7 MB 229.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.8/1.7 MB 229.8 kB/s eta 0:00:05
   ------------------------ --------------- 1.0/1.7 MB 239.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.0/1.7 MB 239.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.0/1.7 MB 239.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.0/1.7 MB 239.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.0/1.7 MB 239.7 kB/s eta 0:00:03
   ------------------------------ --------- 1.3/1.7 MB 232.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.3/1.7 MB 232.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.3/1.7 MB 232.2 kB/s eta 0:00:02
   ------------------------------------ --- 1.6/1.7 MB 255.0 kB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 255.0 kB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 266.1 kB/s eta 0:00:00
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-1.0.0-py3-none-any.whl (50 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading blis-1.3.3-cp312-cp312-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.2 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.2 MB 882.6 kB/s eta 0:00:07
   ----- ---------------------------------- 0.8/6.2 MB 1.0 MB/s eta 0:00:06
   ------ --------------------------------- 1.0/6.2 MB 1.1 MB/s eta 0:00:05
   -------- ------------------------------- 1.3/6.2 MB 1.0 MB/s eta 0:00:05
   ---------- ----------------------------- 1.6/6.2 MB 1.1 MB/s eta 0:00:05
   ------------- -------------------------- 2.1/6.2 MB 1.2 MB/s eta 0:00:04
   --------------- ------------------------ 2.4/6.2 MB 1.3 MB/s eta 0:00:03
   ---------------- ----------------------- 2.6/6.2 MB 1.4 MB/s eta 0:00:03
   ---------------- ----------------------- 2.6/6.2 MB 1.4 MB/s eta 0:00:03
   ------------------ --------------------- 2.9/6.2 MB 1.2 MB/s eta 0:00:03
   -------------------- ------------------- 3.1/6.2 MB 1.2 MB/s eta 0:00:03
   -------------------- ------------------- 3.1/6.2 MB 1.2 MB/s eta 0:00:03

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [126]:
import sys
# The extra quotes around {sys.executable} handle the space in your folder path
!"{sys.executable}" -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - ------------------------------------- 0.5/12.8 MB 644.1 kB/s eta 0:00:20
     -- ------------------------------------- 0.8/12.8 MB 1.0 MB/s eta 0:00:12
     ---- ----------------------------------- 1.3/12.8 MB 1.4 MB/s eta 0:00:09
     ---- ----------------------------------- 1.3/12.8 MB 1.4 MB/s eta 0:00:09
     ---- ----------------------------------- 1.6/12.8 MB 1.2 MB/s eta 0:00:10
     ---- ----------------------------------- 1.6/12.8 MB 1.2 MB/s eta 0:00:10
     ----- ---------------------------------- 1.8/12.8 MB 1.0 MB/s eta 0:00:11
     ------- -------------------------------- 2.4/12.8 MB 1.1 MB/s eta 0:00:10
     ------- -------------------------------- 2.4/12.8 MB 1.1 MB/s eta 0:00:10
     --------- ------------------------------ 2.9/12.8 MB 1.1 MB/s eta 0:00:09
     --------- ------------------------------ 2.9/12.8 MB 1.1 MB/s eta 0:00:09
     --------- ------------------------------ 3.1/12.8 MB 1.1 MB/s eta 0:00:09
     ---------- ----------------------------- 3.4/12.8 MB 1.1 MB/s eta 0:00:09
     ----------- ---------------------------- 3.7/12.8 MB 1.1 MB/s eta 0:00:09
     ------------- -------------------------- 4.2/12.8 MB 1.2 MB/s eta 0:00:08
     ------------- -------------------------- 4.5/12.8 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.7/12.8 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 5.0/12.8 MB 1.2 MB/s eta 0:00:07
     ---------------- ----------------------- 5.2/12.8 MB 1.2 MB/s eta 0:00:07
     ----------------- ---------------------- 5.5/12.8 MB 1.2 MB/s eta 0:00:07
     ------------------ --------------------- 5.8/12.8 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 5.8/12.8 MB 1.2 MB/s eta 0:00:06
     ------------------ --------------------- 6.0/12.8 MB 1.2 MB/s eta 0:00:06
     -------------------- ------------------- 6.6/12.8 MB 1.2 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.8 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 7.3/12.8 MB 1.3 MB/s eta 0:00:05
     ------------------------ --------------- 7.9/12.8 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 8.1/12.8 MB 1.3 MB/s eta 0:00:04
     --------------------------- ------------ 8.7/12.8 MB 1.3 MB/s eta 0:00:04
     --------------------------- ------------ 8.9/12.8 MB 1.4 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.8 MB 1.4 MB/s eta 0:00:03
     ------------------------------- -------- 10.0/12.8 MB 1.4 MB/s eta 0:00:03
     ------------------------------- -------- 10.0/12.8 MB 1.4 MB/s eta 0:00:03
     -------------------------------- ------- 10.5/12.8 MB 1.4 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 1.4 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.4 MB/s eta 0:00:02
     ------------------------------------ --- 11.5/12.8 MB 1.4 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 1.4 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 1.4 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 1.4 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [127]:
import spacy
from spacy.util import is_package

print(is_package("en_core_web_sm"))

True

In [131]:
# Spacy

import spacy
# Load the model
nlp = spacy.load('en_core_web_sm')

In [134]:
sent1 = 'I am going to New Delhi'
doc1 = nlp(sent1)

tokens = [token.text for token in doc1]
print(tokens)

['I', 'am', 'going', 'to', 'New', 'Delhi']

# Stemmer

In [136]:
from nltk.stem.porter import PorterStemmer

In [137]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [139]:
sample = 'play played playing'
stem_words(sample)        # convert into root word, and sometimes it's not readable. lemmatization can handle this.

'play play play'

# lemmatization

In [141]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

wordnet_lemmatizer = WordNetLemmatizer()

sentence = 'He was running and eating at the same time. He has bad habit of swimming after playing long hours in the ground'
punctuations = "?:!.,;"

# Tokenize
sent_words = nltk.word_tokenize(sentence)

filtered_words = [word for word in sent_words if word not in punctuations]

# Print header
print("{0:20}{1:20}".format('Word', 'Lemma'))

# Print results
for word in filtered_words:
    print("{0:20}{1:20}".format(word, wordnet_lemmatizer.lemmatize(word, pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
the                 the
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
ground              grind

> Note : Stemming and Lemmatization are same to retrieve root words but lemmatization is worked good, lemmatization is slow and stemming is fast