In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({'text':['pokemon is a anime',
                           'ash i a pokemon trainer',
                           'a pokemon trainer hunts pokemon',
                           'everytime there is win'],'output':[1,1,0,0]})

df

                              text  output
0               pokemon is a anime       1
1          ash i a pokemon trainer       1
2  a pokemon trainer hunts pokemon       0
3           everytime there is win       0

In [11]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from scikit-learn) (2.5.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: joblib>=1.4.0 in c:\users\amanp\onedrive\desktop\gen ai\module1\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Downloading scipy-1.18.0-cp312-cp312-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.6 MB 645.7 kB/s eta 0:00:56
    --------------------------------------- 0.8/36.6 MB 211.1 kB/s eta 0:02:50
    --------------------------------------- 0.8/36.6 MB 211.1 kB/s eta 0:02:50
    --------------------------------------- 0.8/36.6 MB 211.1 kB/s eta 0:02:50
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.0/36.6 MB 251.7 kB/s eta 0:02:22
   - -------------------------------------- 1.3/36.6 MB 223.0 kB/s eta 0:02:39
   - -------------------------------------- 1.3/36.6 MB 223.0 kB/s eta 0:02:39
   - -------------------------------------- 1.6/36.6 MB 248.2 kB/s eta 0:02:22
   - -------------------------------------- 1.6/36.6 MB 248.2 kB/s eta 0:02:22
   -- ------------------------------------- 1.8/36.6 MB 283.6 kB/s eta 0:02:03
   -- ------------------------------------- 2.4/36.6 MB 357.9 kB/s eta 0:01:36
   -- ------------------------------------- 2.6/36.6 MB 393.2 kB/s eta 0:01:27
   -- ------------------------------------- 2.6/36.6 MB 393.2 kB/s eta 0:01:27
   -- ------------------------------------- 2.6/36.6 MB 393.2 kB/s eta 0:01:27
   -- ------------------------------------- 2.6/36.6 MB 393.2 kB/s eta 0:01:27
   -- ------------------------------------- 2.6/36.6 MB 393.2 kB/s eta 0:01:27
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 2.9/36.6 MB 369.5 kB/s eta 0:01:32
   --- ------------------------------------ 3.1/36.6 MB 314.9 kB/s eta 0:01:47
   --- ------------------------------------ 3.4/36.6 MB 337.8 kB/s eta 0:01:39
   ---- ----------------------------------- 3.7/36.6 MB 350.6 kB/s eta 0:01:34
   ---- ----------------------------------- 3.7/36.6 MB 350.6 kB/s eta 0:01:34
   ---- ----------------------------------- 3.9/36.6 MB 363.0 kB/s eta 0:01:30
   ---- ----------------------------------- 4.5/36.6 MB 405.5 kB/s eta 0:01:20
   ----- ---------------------------------- 5.0/36.6 MB 448.1 kB/s eta 0:01:11
   ------ --------------------------------- 5.5/36.6 MB 488.4 kB/s eta 0:01:04
   ------ --------------------------------- 6.0/36.6 MB 525.8 kB/s eta 0:00:59
   ------- -------------------------------- 6.6/36.6 MB 562.3 kB/s eta 0:00:54
   ------- -------------------------------- 7.1/36.6 MB 599.2 kB/s eta 0:00:50
   -------- ------------------------------- 7.9/36.6 MB 653.1 kB/s eta 0:00:44
   --------- ------------------------------ 8.4/36.6 MB 688.9 kB/s eta 0:00:41
   ---------- ----------------------------- 9.2/36.6 MB 741.8 kB/s eta 0:00:37
   ---------- ----------------------------- 9.7/36.6 MB 774.3 kB/s eta 0:00:35
   ----------- ---------------------------- 10.5/36.6 MB 819.9 kB/s eta 0:00:32
   ------------ --------------------------- 11.0/36.6 MB 848.2 kB/s eta 0:00:31
   ------------ --------------------------- 11.5/36.6 MB 875.5 kB/s eta 0:00:29
   ------------- -------------------------- 12.1/36.6 MB 898.8 kB/s eta 0:00:28
   ------------- -------------------------- 12.3/36.6 MB 906.9 kB/s eta 0:00:27
   ------------- -------------------------- 12.6/36.6 MB 915.8 kB/s eta 0:00:27
   -------------- ------------------------- 13.1/36.6 MB 936.3 kB/s eta 0:00:26
   -------------- ------------------------- 13.4/36.6 MB 945.8 kB/s eta 0:00:25
   --------------- ------------------------ 13.9/36.6 MB 967.2 kB/s eta 0:00:24
   --------------- ------------------------ 14.2/36.6 MB 975.0 kB/s eta 0:00:24
   --------------- ------------------------ 14.4/36.6 MB 976.3 kB/s eta 0:00:23
   ---------------- ----------------------- 14.7/36.6 MB 979.5 kB/s eta 0:00:23
   ---------------- ----------------------- 15.2/36.6 MB 1.0 MB/s eta 0:00:22
   ----------------- ---------------------- 15.7/36.6 MB 1.0 MB/s eta 0:00:21
   ----------------- ---------------------- 16.3/36.6 MB 1.0 MB/s eta 0:00:20
   ------------------ --------------------- 16.5/36.6 MB 1.0 MB/s eta 0:00:20
   ------------------ --------------------- 16.8/36.6 MB 1.0 MB/s eta 0:00:19
   ------------------ --------------------- 17.0/36.6 MB 1.1 MB/s eta 0:00:19
   ------------------- -------------------- 17.6/36.6 MB 1.1 MB/s eta 0:00:18
   ------------------- -------------------- 17.8/36.6 MB 1.1 MB/s eta 0:00:18
   ------------------- -------------------- 18.1/36.6 MB 1.1 MB/s eta 0:00:18
   -------------------- ------------------- 18.6/36.6 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 18.9/36.6 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 18.9/36.6 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.1/36.6 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.4/36.6 MB 1.1 MB/s eta 0:00:16
   --------------------- ------------------ 19.7/36.6 MB 1.1 MB/s eta 0:00:16
   --------------------- ------------------ 19.9/36.6 MB 1.1 MB/s eta 0:00:16
   ---------------------- ----------------- 20.4/36.6 MB 1.1 MB/s eta 0:00:15
   ---------------------- ----------------- 21.0/36.6 MB 1.1 MB/s eta 0:00:15
   ----------------------- ---------------- 21.5/36.6 MB 1.1 MB/s eta 0:00:14
   ----------------------- ---------------- 21.8/36.6 MB 1.1 MB/s eta 0:00:14
   ------------------------ --------------- 22.0/36.6 MB 1.1 MB/s eta 0:00:13
   ------------------------ --------------- 22.3/36.6 MB 1.1 MB/s eta 0:00:13
   ------------------------ --------------- 22.5/36.6 MB 1.1 MB/s eta 0:00:13
   ------------------------- -------------- 23.1/36.6 MB 1.1 MB/s eta 0:00:12
   ------------------------- -------------- 23.6/36.6 MB 1.2 MB/s eta 0:00:12
   -------------------------- ------------- 23.9/36.6 MB 1.2 MB/s eta 0:00:11
   -------------------------- ------------- 24.1/36.6 MB 1.2 MB/s eta 0:00:11
   -------------------------- ------------- 24.6/36.6 MB 1.2 MB/s eta 0:00:11
   --------------------------- ------------ 24.9/36.6 MB 1.2 MB/s eta 0:00:10
   --------------------------- ------------ 25.2/36.6 MB 1.2 MB/s eta 0:00:10
   ---------------------------- ----------- 25.7/36.6 MB 1.2 MB/s eta 0:00:10
   ---------------------------- ----------- 26.0/36.6 MB 1.2 MB/s eta 0:00:09
   ---------------------------- ----------- 26.2/36.6 MB 1.2 MB/s eta 0:00:09
   ---------------------------- ----------- 26.5/36.6 MB 1.2 MB/s eta 0:00:09
   ----------------------------- ---------- 26.7/36.6 MB 1.2 MB/s eta 0:00:09
   ----------------------------- ---------- 27.3/36.6 MB 1.2 MB/s eta 0:00:08
   ------------------------------ --------- 27.5/36.6 MB 1.2 MB/s eta 0:00:08
   ------------------------------ --------- 28.0/36.6 MB 1.2 MB/s eta 0:00:08
   ------------------------------ --------- 28.3/36.6 MB 1.2 MB/s eta 0:00:07
   ------------------------------- -------- 28.8/36.6 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 29.4/36.6 MB 1.2 MB/s eta 0:00:06
   -------------------------------- ------- 29.9/36.6 MB 1.2 MB/s eta 0:00:06
   -------------------------------- ------- 30.1/36.6 MB 1.2 MB/s eta 0:00:06
   --------------------------------- ------ 30.7/36.6 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 31.2/36.6 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 31.7/36.6 MB 1.3 MB/s eta 0:00:04
   ----------------------------------- ---- 32.5/36.6 MB 1.3 MB/s eta 0:00:04
   ------------------------------------ --- 33.0/36.6 MB 1.3 MB/s eta 0:00:03
   ------------------------------------ --- 33.8/36.6 MB 1.3 MB/s eta 0:00:03
   ------------------------------------- -- 34.6/36.6 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 35.4/36.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 1.4 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, scikit-learn
Successfully installed narwhals-2.23.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\amanp\OneDrive\Desktop\Gen AI\module1\.venv\Scripts\python.exe -m pip install --upgrade pip

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [14]:
# bow
bow = cv.fit_transform(df['text'])

In [15]:
# vocabulary
print(cv.vocabulary_)

{'pokemon': 5, 'is': 4, 'anime': 0, 'ash': 1, 'trainer': 7, 'hunts': 3, 'everytime': 2, 'there': 6, 'win': 8}

In [16]:
bow.toarray()

array([[1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 2, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 1]])

In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 0 0 1 1 0 0 0]]
[[0 1 0 0 0 1 0 1 0]]
[[0 0 0 1 0 2 0 1 0]]
[[0 0 1 0 1 0 1 0 1]]

In [18]:
# new data
cv.transform(['Garry Watch Ash']).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
X = bow.toarray()
y = df['output']

In [20]:
# TF - IDF (term freq - inverse document frequency)

df = pd.DataFrame({'text':['pokemon is a anime',
                           'ash i a pokemon trainer',
                           'a pokemon trainer hunts pokemon',
                           'everytime there is win'],'output':[1,1,0,0]})

df

                              text  output
0               pokemon is a anime       1
1          ash i a pokemon trainer       1
2  a pokemon trainer hunts pokemon       0
3           everytime there is win       0

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer()

In [25]:
arr = tfid.fit_transform(df['text']).toarray()

In [26]:
arr

array([[0.70203482, 0.        , 0.        , 0.        , 0.55349232,
        0.44809973, 0.        , 0.        , 0.        ],
       [0.        , 0.70203482, 0.        , 0.        , 0.        ,
        0.44809973, 0.        , 0.55349232, 0.        ],
       [0.        , 0.        , 0.        , 0.55459491, 0.        ,
        0.7079815 , 0.        , 0.437249  , 0.        ],
       [0.        , 0.        , 0.52547275, 0.        , 0.41428875,
        0.        , 0.52547275, 0.        , 0.52547275]])

In [28]:
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.51082562 1.22314355
 1.91629073 1.51082562 1.91629073]